import { BgImageFileName } from "../components/common/background-image/background-image";

export const PROJECTS_DATA_CARD_LIST = [
  {
    id: "01",
    title: "data.project.rocco_website.title",
    bgCard: BgImageFileName.ROCCO_WEBSITE,
    extraCss: "wide",
    companyName: "data.project.rocco_website.company_name",
    companyLinkURL: "https://theghost1980.github.io/roccoOldSite/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.rocco_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "02",
    title: "data.project.old_portfolio_website.title",
    bgCard: BgImageFileName.OLD_PORTFOLIO_WEBSITE,
    extraCss: "tall",
    companyName: "data.project.old_portfolio_website.company_name",
    companyLinkURL: "https://frosty-poincare-a18064.netlify.app/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.rocco_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "03",
    title: "data.project.jobaboard_website.title",
    bgCard: BgImageFileName.JOBABOARD_WEBSITE,
    extraCss: "wide",
    companyName: "data.project.jobaboard_website.company_name",
    companyLinkURL: "https://awesome-hoover-fbbbdc.netlify.app/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.jobaboard_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "04",
    title: "data.project.nansystems_website.title",
    bgCard: BgImageFileName.NANSYSTEMS_WEBSITE,
    extraCss: "tall",
    companyName: "data.project.nansystems_website.company_name",
    companyLinkURL: "https://nansystems.us/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.nansystems_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "05",
    title: "data.project.landing_website.title",
    bgCard: BgImageFileName.LANDING_WEBSITE,
    extraCss: "tall",
    companyName: "data.project.landing_website.company_name",
    companyLinkURL: "https://cranky-blackwell-3641eb.netlify.app/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.landing_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "06",
    title: "data.project.keychain_ci.title",
    bgCard: BgImageFileName.KEYCHAIN_CI,
    extraCss: "wide",
    companyName: "data.project.keychain_ci.company_name",
    companyLinkURL:
      "https://github.com/hive-keychain/hive-keychain-extension/tree/tests/fix-tests-17022023/src/__tests__",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.landing_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "07",
    title: "data.project.keychain_store.title",
    bgCard: BgImageFileName.KEYCHAIN_STORE,
    // extraCss: "wide",
    companyName: "data.project.keychain_store.company_name",
    companyLinkURL: "https://github.com/hive-keychain/keychain-store",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_store.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "08",
    title: "data.project.keychain_playground_website.title",
    bgCard: BgImageFileName.KEYCHAIN_PLAYGROUND,
    extraCss: "wide",
    companyName: "data.project.keychain_playground_website.company_name",
    companyLinkURL: "https://play.hive-keychain.com/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_playground_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "09",
    title: "data.project.keychain_widget_website.title",
    bgCard: BgImageFileName.KEYCHAIN_WIDGET_WEBSITE,
    // extraCss: "wide",
    companyName: "data.project.keychain_widget_website.company_name",
    companyLinkURL:
      "https://swapwidget.hive-keychain.com/?username=theghost1980",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_widget_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "10",
    title: "data.project.keychain_sdk.title",
    bgCard: BgImageFileName.KEYCHAIN_SDK,
    // extraCss: "wide",
    companyName: "data.project.keychain_sdk.company_name",
    companyLinkURL: "https://github.com/hive-keychain/keychain-sdk",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_sdk.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "11",
    title: "data.project.keychain_tutorial_website.title",
    bgCard: BgImageFileName.KEYCHAIN_TUTORIAL_WEBSITE,
    // extraCss: "wide",
    companyName: "data.project.keychain_tutorial_website.company_name",
    companyLinkURL: "https://tutorial.hive-keychain.com/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_tutorial_website.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "12",
    title: "data.project.keychain_mobile_widgets.title",
    bgCard: BgImageFileName.KEYCHAIN_MOBILE_WIDGETS,
    extraCss: "tall",
    companyName: "data.project.keychain_mobile_widgets.company_name",
    companyLinkURL:
      "https://github.com/hive-keychain/hive-keychain-mobile/tree/dev/android/app/src/main/java/com/mobilekeychain",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_mobile_widgets.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "13",
    title: "data.project.keychain_mobile_newui.title",
    bgCard: BgImageFileName.KEYCHAIN_MOBILE_NEWUI,
    extraCss: "tall",
    companyName: "data.project.keychain_mobile_newui.company_name",
    companyLinkURL:
      "https://play.google.com/store/search?q=keychain&c=apps&hl=es_419",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_mobile_newui.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "14",
    title: "data.project.keychain_extension_portfolio.title",
    bgCard: BgImageFileName.KEYCHAIN_EXTENSION_PORTFOLIO,
    // extraCss: "tall",
    companyName: "data.project.keychain_extension_portfolio.company_name",
    companyLinkURL:
      "https://github.com/hive-keychain/hive-keychain-extension/blob/master/src/portfolio/portfolio.component.tsx",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.keychain_extension_portfolio.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
  {
    id: "15",
    title: "data.project.first_cv_portfolio.title",
    bgCard: BgImageFileName.FIRST_CV_PORTFOLIO,
    // extraCss: "tall",
    companyName: "data.project.first_cv_portfolio.company_name",
    companyLinkURL: "https://theghost1980.github.io/google-homepage/",
    // position: "data.work_experience.keychain.position",
    // time: "data.work_experience.keychain.time",
    description: "data.project.first_cv_portfolio.description",
    project_key_points: ["one", "two", "three"],
    // acomplishments: [
    //   "data.work_experience.keychain.acomplishment_1",
    //   "data.work_experience.keychain.acomplishment_2",
    //   "data.work_experience.keychain.acomplishment_3",
    // ],
    images: [
      "./assets/images/work/keychain/keychain-work-1.png",
      "./assets/images/work/keychain/keychain-work-2.png",
    ],
  },
];
