import { BgImageFileName } from "../components/common/background-image/background-image";
import { IconPathName } from "../components/common/icon/icon";

export const PROJECTS_DATA_CARD_LIST = [
  {
    id: "01",
    title: "data.project.rocco_website.title",
    bgCard: BgImageFileName.ROCCO_WEBSITE,
    extraCss: "wide",
    companyName: "data.project.rocco_website.company_name",
    companyLinkURL: "https://theghost1980.github.io/roccoOldSite/",
    projectLinkCode: "https://github.com/theghost1980/roccoOldSite",
    description: "data.project.rocco_website.description",
    tech_stack: [
      IconPathName.TYPESCRIPT,
      IconPathName.REACT,
      IconPathName.JAVASCRIPT,
      IconPathName.HTML_5,
      IconPathName.GITHUB,
      IconPathName.CSS_3,
    ],
    images: [
      "./assets/images/projects/rocco/rocco-1.png",
      "./assets/images/projects/rocco/rocco-2.png",
      "./assets/images/projects/rocco/rocco-3.png",
      "./assets/images/projects/rocco/rocco-4.png",
    ],
  },
  {
    id: "02",
    title: "data.project.old_portfolio_website.title",
    bgCard: BgImageFileName.OLD_PORTFOLIO_WEBSITE,
    extraCss: "tall",
    companyName: "data.project.old_portfolio_website.company_name",
    companyLinkURL: "https://frosty-poincare-a18064.netlify.app/",
    projectLinkCode: "https://github.com/theghost1980/newportfolio",
    description: "data.project.old_portfolio_website.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.JAVASCRIPT,
      IconPathName.HTML_5,
      IconPathName.GITHUB,
      IconPathName.CSS_3,
      IconPathName.PAYPAL,
      IconPathName.EMAIL,
    ],
    images: [
      "./assets/images/projects/old-portfolio/old-portfolio-1.png",
      "./assets/images/projects/old-portfolio/old-portfolio-2.png",
      "./assets/images/projects/old-portfolio/old-portfolio-3.png",
      "./assets/images/projects/old-portfolio/old-portfolio-4.png",
      "./assets/images/projects/old-portfolio/old-portfolio-5.png",
    ],
  },
  {
    id: "03",
    title: "data.project.jobaboard_website.title",
    bgCard: BgImageFileName.JOBABOARD_WEBSITE,
    extraCss: "wide",
    companyName: "data.project.jobaboard_website.company_name",
    companyLinkURL: "https://awesome-hoover-fbbbdc.netlify.app/",
    projectLinkCode: "https://github.com/theghost1980/jobaboard",
    description: "data.project.jobaboard_website.description",
    tech_stack: [
      IconPathName.NODEJS,
      IconPathName.MONGO,
      IconPathName.REACT,
      IconPathName.GATSBY,
      IconPathName.BLOCKCHAIN,
      IconPathName.HEROKU,
      IconPathName.CDN,
    ],
    images: [
      "./assets/images/projects/jobaboard/jobaboard-1.png",
      "./assets/images/projects/jobaboard/jobaboard-2.png",
      "./assets/images/projects/jobaboard/jobaboard-3.png",
      "./assets/images/projects/jobaboard/jobaboard-4.png",
    ],
  },
  {
    id: "04",
    title: "data.project.nansystems_website.title",
    bgCard: BgImageFileName.NANSYSTEMS_WEBSITE,
    extraCss: "tall",
    companyName: "data.project.nansystems_website.company_name",
    companyLinkURL: "https://nansystems.us/",
    projectLinkCode: "https://github.com/theghost1980/testNanSystems",
    description: "data.project.nansystems_website.description",
    tech_stack: [
      IconPathName.GRAPHQL,
      IconPathName.CONTENTFUL,
      IconPathName.GATSBY,
      IconPathName.REACT,
      IconPathName.CSS_3,
      IconPathName.EMAIL,
      IconPathName.NETLIFY,
    ],
    images: [
      "./assets/images/projects/nansystems/nansystems-1.png",
      "./assets/images/projects/nansystems/nansystems-2.png",
      "./assets/images/projects/nansystems/nansystems-3.png",
      "./assets/images/projects/nansystems/nansystems-4.png",
    ],
  },
  {
    id: "05",
    title: "data.project.landing_website.title",
    bgCard: BgImageFileName.LANDING_WEBSITE,
    extraCss: "tall",
    companyName: "data.project.landing_website.company_name",
    companyLinkURL: "https://cranky-blackwell-3641eb.netlify.app/",
    projectLinkCode: "https://github.com/theghost1980/landingpage",
    description: "data.project.landing_website.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.GATSBY,
      IconPathName.CSS_3,
      IconPathName.HTML_5,
      IconPathName.NETLIFY,
    ],
    images: [
      "./assets/images/projects/landing/landing-1.png",
      "./assets/images/projects/landing/landing-2.png",
      "./assets/images/projects/landing/landing-3.png",
      "./assets/images/projects/landing/landing-4.png",
    ],
  },
  {
    id: "06",
    title: "data.project.keychain_ci.title",
    bgCard: BgImageFileName.KEYCHAIN_CI,
    extraCss: "wide",
    companyName: "data.project.keychain_ci.company_name",
    companyLinkURL:
      "https://github.com/hive-keychain/hive-keychain-extension/tree/tests/fix-tests-17022023/src/__tests__",
    projectLinkCode:
      "https://github.com/hive-keychain/hive-keychain-extension/blob/tests/fix-tests-17022023/src/__tests__/content-scripts/web-interface/response.logic.test.ts",
    description: "data.project.keychain_ci.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.JEST,
      IconPathName.RTL,
      IconPathName.WEBPACK,
      IconPathName.GITHUB,
    ],
    images: [
      "./assets/images/projects/ci-test/ci-test-1.png",
      "./assets/images/projects/ci-test/ci-test-2.png",
      "./assets/images/projects/ci-test/ci-test-3.png",
    ],
  },
  {
    id: "07",
    title: "data.project.keychain_store.title",
    bgCard: BgImageFileName.KEYCHAIN_STORE,
    companyName: "data.project.keychain_store.company_name",
    companyLinkURL:
      "https://play.google.com/store/apps/details?id=com.keychainstore&hl=es_419",
    projectLinkCode: "https://github.com/hive-keychain/keychain-store",
    description: "data.project.keychain_store.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.ANDROID,
      IconPathName.BLOCKCHAIN,
      IconPathName.PLAYSTORE,
    ],
    images: [
      "./assets/images/projects/keychain-store/keychain-store-1.png",
      "./assets/images/projects/keychain-store/keychain-store-2.png",
      "./assets/images/projects/keychain-store/keychain-store-3.png",
    ],
  },
  {
    id: "08",
    title: "data.project.keychain_playground_website.title",
    bgCard: BgImageFileName.KEYCHAIN_PLAYGROUND,
    extraCss: "wide",
    companyName: "data.project.keychain_playground_website.company_name",
    companyLinkURL: "https://play.hive-keychain.com/",
    projectLinkCode: "https://github.com/hive-keychain/keychain-sdk-playground",
    description: "data.project.keychain_playground_website.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.BLOCKCHAIN,
      IconPathName.JAVASCRIPT,
      IconPathName.BOOTSTRAP,
      IconPathName.SDK,
    ],
    images: [
      "./assets/images/projects/keychain-playground/keychain-playground-1.png",
      "./assets/images/projects/keychain-playground/keychain-playground-2.png",
    ],
  },
  {
    id: "09",
    title: "data.project.keychain_widget_website.title",
    bgCard: BgImageFileName.KEYCHAIN_WIDGET_WEBSITE,
    companyName: "data.project.keychain_widget_website.company_name",
    companyLinkURL:
      "https://swapwidget.hive-keychain.com/?username=theghost1980",
    projectLinkCode: "https://github.com/hive-keychain/swap-widget",
    description: "data.project.keychain_widget_website.description",
    tech_stack: [
      IconPathName.ANDROID,
      IconPathName.ANDROID_STUDIO,
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.BLOCKCHAIN,
      IconPathName.WEBPACK,
    ],
    images: ["./assets/images/projects/keychain-widget/keychain-widget-1.png"],
  },
  {
    id: "10",
    title: "data.project.keychain_sdk.title",
    bgCard: BgImageFileName.KEYCHAIN_SDK,
    companyName: "data.project.keychain_sdk.company_name",
    companyLinkURL: "https://github.com/hive-keychain/keychain-sdk",
    projectLinkCode: "https://github.com/hive-keychain/keychain-sdk",
    description: "data.project.keychain_sdk.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.BLOCKCHAIN,
      IconPathName.WEBPACK,
      IconPathName.NPM,
    ],
    images: [
      "./assets/images/projects/keychain-sdk/keychain-sdk-1.png",
      "./assets/images/projects/keychain-sdk/keychain-sdk-2.png",
    ],
  },
  {
    id: "11",
    title: "data.project.keychain_tutorial_website.title",
    bgCard: BgImageFileName.KEYCHAIN_TUTORIAL_WEBSITE,
    companyName: "data.project.keychain_tutorial_website.company_name",
    companyLinkURL: "https://tutorial.hive-keychain.com/",
    projectLinkCode: "https://github.com/hive-keychain/tutorial",
    description: "data.project.keychain_tutorial_website.description",
    tech_stack: [
      IconPathName.GITHUB_PAGES,
      IconPathName.GITHUB,
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.ANDROID,
    ],
    images: [
      "./assets/images/projects/keychain-tutorial/keychain-tutorial-1.png",
      "./assets/images/projects/keychain-tutorial/keychain-tutorial-2.png",
      "./assets/images/projects/keychain-tutorial/keychain-tutorial-3.png",
    ],
  },
  {
    id: "12",
    title: "data.project.keychain_mobile_widgets.title",
    bgCard: BgImageFileName.KEYCHAIN_MOBILE_WIDGETS,
    extraCss: "tall",
    companyName: "data.project.keychain_mobile_widgets.company_name",
    companyLinkURL:
      "https://github.com/hive-keychain/hive-keychain-mobile/tree/dev/android/app/src/main/java/com/mobilekeychain",
    projectLinkCode:
      "https://github.com/hive-keychain/hive-keychain-mobile/blob/dev/android/app/src/main/java/com/mobilekeychain/WidgetCurrencyListService.java",
    description: "data.project.keychain_mobile_widgets.description",
    tech_stack: [
      IconPathName.JAVA,
      IconPathName.ANDROID,
      IconPathName.ANDROID_STUDIO,
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
    ],
    images: [
      "./assets/images/projects/keychain-mobile-widget/keychain-mobile-widget-1.png",
    ],
  },
  {
    id: "13",
    title: "data.project.keychain_mobile_newui.title",
    bgCard: BgImageFileName.KEYCHAIN_MOBILE_NEWUI,
    extraCss: "tall",
    companyName: "data.project.keychain_mobile_newui.company_name",
    companyLinkURL:
      "https://play.google.com/store/search?q=keychain&c=apps&hl=es_419",
    projectLinkCode: "https://github.com/hive-keychain/hive-keychain-mobile",
    description: "data.project.keychain_mobile_newui.description",
    tech_stack: [
      IconPathName.JAVA,
      IconPathName.ANDROID,
      IconPathName.ANDROID_STUDIO,
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.FIGMA,
    ],
    images: [
      "./assets/images/projects/keychain-new-ui/keychain-new-ui-1.png",
      "./assets/images/projects/keychain-new-ui/keychain-new-ui-2.png",
    ],
  },
  {
    id: "14",
    title: "data.project.keychain_extension_portfolio.title",
    bgCard: BgImageFileName.KEYCHAIN_EXTENSION_PORTFOLIO,
    companyName: "data.project.keychain_extension_portfolio.company_name",
    companyLinkURL:
      "https://github.com/hive-keychain/hive-keychain-extension/blob/master/src/portfolio/portfolio.component.tsx",
    projectLinkCode:
      "https://github.com/hive-keychain/hive-keychain-extension/tree/master/src/portfolio",
    description: "data.project.keychain_extension_portfolio.description",
    tech_stack: [
      IconPathName.REACT,
      IconPathName.TYPESCRIPT,
      IconPathName.CHROME,
      IconPathName.CSS_3,
      IconPathName.JAVASCRIPT,
      IconPathName.BLOCKCHAIN,
      IconPathName.HTML_5,
    ],
    images: [
      "./assets/images/projects/keychain-portfolio/keychain-portfolio-1.png",
      "./assets/images/projects/keychain-portfolio/keychain-portfolio-2.png",
      "./assets/images/projects/keychain-portfolio/keychain-portfolio-3.png",
    ],
  },
  {
    id: "15",
    title: "data.project.first_cv_portfolio.title",
    bgCard: BgImageFileName.FIRST_CV_PORTFOLIO,
    companyName: "data.project.first_cv_portfolio.company_name",
    companyLinkURL: "https://theghost1980.github.io/google-homepage/",
    projectLinkCode: "https://github.com/theghost1980/google-homepage",
    description: "data.project.first_cv_portfolio.description",
    tech_stack: [IconPathName.HTML_5, IconPathName.CSS_3, IconPathName.GITHUB],
    images: [
      "./assets/images/projects/first-portfolio/first-portfolio-1.png",
      "./assets/images/projects/first-portfolio/first-portfolio-2.png",
    ],
  },
];
